import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { PostPayload } from '../types';

export interface SupabaseConfig {
  url: string;
  anonKey: string;
  tableName: string;
}

export const DEFAULT_SUPABASE_TABLE = 'evaluaciones_pgirs';

// SQL script for user to copy & paste in Supabase SQL Editor
export const SUPABASE_SQL_SCRIPT = `-- Copiar y ejecutar en el SQL Editor de tu proyecto en Supabase:

CREATE TABLE IF NOT EXISTS evaluaciones_pgirs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  cargo TEXT NOT NULL,
  nota TEXT NOT NULL,
  porcentaje TEXT NOT NULL,
  fecha TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Deshabilitar RLS para permitir inserciones directas con la clave anon (o definir políticas):
ALTER TABLE evaluaciones_pgirs DISABLE ROW LEVEL SECURITY;
`;

/**
 * Creates a Supabase client dynamically if valid URL and anonKey are provided.
 */
export function getSupabaseClient(url: string, anonKey: string): SupabaseClient | null {
  const cleanUrl = url?.trim();
  const cleanKey = anonKey?.trim();

  if (!cleanUrl || !cleanKey || !cleanUrl.startsWith('http')) {
    return null;
  }

  try {
    return createClient(cleanUrl, cleanKey);
  } catch (error) {
    console.error('Error creando cliente Supabase:', error);
    return null;
  }
}

/**
 * Inserts an evaluation record into Supabase.
 */
export async function insertEvaluacionSupabase(
  config: SupabaseConfig,
  payload: PostPayload
): Promise<{ success: boolean; message: string; error?: any }> {
  const client = getSupabaseClient(config.url, config.anonKey);

  if (!client) {
    return {
      success: false,
      message: 'Configuración de Supabase incompleta. Por favor verifique la URL y la Anon Key.'
    };
  }

  const tableName = config.tableName?.trim() || DEFAULT_SUPABASE_TABLE;

  try {
    const { data, error } = await client
      .from(tableName)
      .insert([
        {
          nombre: payload.nombre,
          cargo: payload.cargo,
          nota: payload.nota,
          porcentaje: payload.porcentaje,
          fecha: payload.fecha,
        }
      ]);

    if (error) {
      console.error('Error insertando en Supabase:', error);
      return {
        success: false,
        message: `Error de Supabase: ${error.message || 'No se pudo registrar la información.'}`,
        error
      };
    }

    return {
      success: true,
      message: '¡Excelente! Los datos se han guardado con éxito en Supabase.'
    };
  } catch (err: any) {
    console.error('Excepción al conectar con Supabase:', err);
    return {
      success: false,
      message: 'Ocurrió una falla de conexión con Supabase.',
      error: err
    };
  }
}

/**
 * Fetches recent evaluation records from Supabase for live viewing inside the app.
 */
export async function fetchEvaluacionesSupabase(
  config: SupabaseConfig
): Promise<{ success: boolean; data?: any[]; message?: string }> {
  const client = getSupabaseClient(config.url, config.anonKey);
  if (!client) {
    return { success: false, message: 'Supabase no está configurado.' };
  }

  const tableName = config.tableName?.trim() || DEFAULT_SUPABASE_TABLE;

  try {
    const { data, error } = await client
      .from(tableName)
      .select('*')
      .order('id', { ascending: false })
      .limit(50);

    if (error) {
      return { success: false, message: error.message };
    }

    return { success: true, data: data || [] };
  } catch (err: any) {
    return { success: false, message: err.message || 'Error al consultar datos' };
  }
}
